#!/bin/sh

exit 0

# Read DHCP host credentials from U-Boot env, fall back to defaults
HOST0_NAME=$(fw_printenv -n dhcp_host0_name 2>/dev/null)
HOST0_MAC=$(fw_printenv -n dhcp_host0_mac 2>/dev/null)
HOST0_DUID=$(fw_printenv -n dhcp_host0_duid 2>/dev/null)

HOST1_NAME=$(fw_printenv -n dhcp_host1_name 2>/dev/null)
HOST1_MAC=$(fw_printenv -n dhcp_host1_mac 2>/dev/null)
HOST1_IP=$(fw_printenv -n dhcp_host1_ip 2>/dev/null)

# Set defaults if any of the values are missing
HOST0_NAME=${HOST0_NAME:-"missing-value-in-uboot"}
HOST0_MAC=${HOST0_MAC:-"00:11:22:33:44:55"}
HOST0_DUID=${HOST0_DUID:-"000000000000000000000000000000000000"}

HOST1_NAME=${HOST1_NAME:-"missing-value-in-uboot"}
HOST1_MAC=${HOST1_MAC:-"00:11:22:33:44:55"}
HOST1_IP=${HOST1_IP:-"192.168.8.55"}

has_host() {
    local name="$1" i=0
    while uci -q get "dhcp.@host[$i]" >/dev/null 2>&1; do
        [ "$(uci -q get "dhcp.@host[$i].name")" = "$name" ] && return 0
        i=$((i + 1))
    done
    return 1
}

# Configure LAN DHCP (odhcpd)
uci set dhcp.lan=dhcp
uci set dhcp.lan.interface='lan'
uci set dhcp.lan.start='100'
uci set dhcp.lan.limit='150'
uci set dhcp.lan.leasetime='12h'
uci set dhcp.lan.dhcpv4='server'
uci set dhcp.lan.dhcpv6='server'
uci set dhcp.lan.ra='server'
uci -q del dhcp.lan.ra_flags
uci add_list dhcp.lan.ra_flags='managed-config'
uci add_list dhcp.lan.ra_flags='other-config'
uci -q del dhcp.lan.dhcp_option
uci add_list dhcp.lan.dhcp_option='3,192.168.8.1'
uci add_list dhcp.lan.dhcp_option='6,192.168.8.1'
uci add_list dhcp.lan.dhcp_option='15,lan'
uci -q del dhcp.lan.dns
uci add_list dhcp.lan.dns='fd08::1'
uci set dhcp.lan.ra_preference='medium'
uci set dhcp.lan.ipv6_only_preferred='0'
uci set dhcp.lan.ra_slaac='0'
uci set dhcp.lan.dhcpv6_pd_preferred='1'
uci set dhcp.lan.dhcpv6_pd='1'

# Ignore WAN DHCP server role
uci set dhcp.wan=dhcp
uci set dhcp.wan.interface='wan'
uci set dhcp.wan.ignore='1'

# Configure odhcpd as main DHCP daemon
uci set dhcp.odhcpd=odhcpd
uci set dhcp.odhcpd.maindhcp='1'
uci set dhcp.odhcpd.leasefile='/var/lib/odhcpd/dhcp.leases'
uci set dhcp.odhcpd.leasetrigger='/usr/lib/unbound/odhcpd.sh'
uci set dhcp.odhcpd.loglevel='4'
uci set dhcp.odhcpd.piodir='/tmp/odhcpd-piodir'
uci set dhcp.odhcpd.hostsdir='/tmp/hosts'

# Add static host: HOST0 (credentials from U-Boot env)
has_host "$HOST0_NAME" || {
    uci -q add dhcp host
    uci -q set dhcp.@host[-1].name="$HOST0_NAME"
    uci -q set dhcp.@host[-1].ip='192.168.8.5'
    uci -q add_list dhcp.@host[-1].mac="$HOST0_MAC"
    uci -q set dhcp.@host[-1].duid="$HOST0_DUID"
    uci -q set dhcp.@host[-1].hostid='05'
}

# Add static host: HOST1 (credentials from U-Boot env)
has_host "$HOST1_NAME" || {
    uci -q add dhcp host
    uci -q set dhcp.@host[-1].name="$HOST1_NAME"
    uci -q set dhcp.@host[-1].ip="$HOST1_IP"
    uci -q add_list dhcp.@host[-1].mac="$HOST1_MAC"
    uci -q set dhcp.@host[-1].hostid='55'
}

uci commit dhcp
exit 0
